name: stage ci
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

  permissions:
    checks: write
    contents: write

  jobs:
    run-linters:
      name: Run linter
      runs-on: ubuntu-24.04

      steps:
        - name: Checkout git repository
          uses: actions/checkout@v4

        - name: Set up NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 22

        - name: Install node dependencies
          run: npm ci

        - name: Run linters
          uses: wearerequired/lint-action@v2
          with:
            eslint: true
            prettier: true
