name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: check out the repository
        uses: actions/checkout@v4
      - name: install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
